addons:
    apt:
        packages:
            - cython
            - python-numpy
            - python-pandas
cache:
    - pip
install:
    - pip install cython
    - pip install -e .
language:
    - python
python:
    - 3.5
script:
    - python setup.py test
