environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python35-x64"

install:
   - "%PYTHON%\\python.exe -m pip install --upgrade --editable .[test]"

build: off

test_script:
  - "%PYTHON%\\python.exe -m pytest"
